import Head from "next/head";

import { Col, Row, Typography } from "antd";
import CustomCard from "@/components/card/Card";

const { Title } = Typography;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>Arrimo Frontend Challenge</Title>
      <Row
        gutter={16}
        justify="center"
        style={{ display: "flex", width: "100%" }}
      >
        <Col span={5}>
          <CustomCard title="Users" href={"/users"}>
            Move to users page
          </CustomCard>
        </Col>
        <Col span={5}>
          <CustomCard title="Calendar" href={"/calendar"}>
            Move to calendar page
          </CustomCard>
        </Col>
      </Row>
    </>
  );
}
